file: "/home/ubuntu/ATAC-seq-peak-calling/files.txt"
download_dir: "/home/ubuntu/ATAC-seq-peak-calling/DATA"
results_dir: "/home/ubuntu/ATAC-seq-peak-calling/Results"
fastqc_dir: "/home/ubuntu/ATAC-seq-peak-calling/Results/fastqc"
multiqc_dir: "/home/ubuntu/ATAC-seq-peak-calling/Results/multiqc"
trim_dir: "/home/ubuntu/ATAC-seq-peak-calling/Results/trim_reads"
align_dir: "/home/ubuntu/ATAC-seq-peak-calling/Results/align_reads"
filter_dir: "/home/ubuntu/ATAC-seq-peak-calling/Results/filter_align_reads"
peak_dir: "/home/ubuntu/ATAC-seq-peak-calling/Results/Peak"
samples:
  sample1:
    pair1: "ENCFF370VYU.fastq.gz"
    pair2: "ENCFF272LNY.fastq.gz"
  sample2:
    pair1: "ENCFF803YGT.fastq.gz"
    pair2: "ENCFF919BOD.fastq.gz"
  sample3:
    pair1: "ENCFF991KGU.fastq.gz"
    pair2: "ENCFF819NFW.fastq.gz"
